package pl.nextsteppro.climbing.domain.activitylog;

public enum ActivityActionType {
    RESERVATION_CREATED,
    RESERVATION_CANCELLED,
    RESERVATION_REACTIVATED,
    EVENT_RESERVATION_CREATED,
    EVENT_RESERVATION_CANCELLED,
    RESERVATION_CANCELLED_BY_ADMIN,
    RESERVATION_UPDATED,
    EVENT_RESERVATION_UPDATED,
    ADMIN_SLOT_CREATED,
    ADMIN_SLOT_UPDATED,
    ADMIN_SLOT_DELETED,
    ADMIN_SLOT_BLOCKED,
    ADMIN_SLOT_UNBLOCKED,
    ADMIN_EVENT_CREATED,
    ADMIN_EVENT_UPDATED,
    ADMIN_EVENT_DELETED,
    ADMIN_USER_MAKE_ADMIN,
    ADMIN_USER_ADMIN_REMOVED,
    ADMIN_USER_DELETED
}
